# -*- coding: utf-8 -*-
"""5cv.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/18iTyJ0wivqz4T6wV6AaLRYUPu_Kw0A1V  
"""

pip install pandas scikit-learn
import pandas as pd
from sklearn.model_selection import cross_val_score, StratifiedKFold
from sklearn.svm import SVC
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier

# Load your dataset (replace 'your_dataset.csv' with the actual file name)
dataset_path = 'your_dataset.csv'
data = pd.read_csv(dataset_path)

# Assuming your features are in columns 'feature1', 'feature2', ..., 'featureN', and the target variable is in 'label'
X = data.drop('label', axis=1)
y = data['label']

# Define classifiers
svm_classifier = SVC(kernel='linear')  # You can modify kernel as needed
lr_classifier = LogisticRegression()
rf_classifier = RandomForestClassifier()

# Define 5-fold cross-validation
cv = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)

# Perform cross-validation for each classifier
svm_scores = cross_val_score(svm_classifier, X, y, cv=cv, scoring='accuracy')
lr_scores = cross_val_score(lr_classifier, X, y, cv=cv, scoring='accuracy')
rf_scores = cross_val_score(rf_classifier, X, y, cv=cv, scoring='accuracy')

# Print the average accuracy for each classifier
print("SVM Accuracy: {:.2f}%".format(svm_scores.mean() * 100))
print("LR Accuracy: {:.2f}%".format(lr_scores.mean() * 100))
print("RF Accuracy: {:.2f}%".format(rf_scores.mean() * 100))
