# -*- coding: utf-8 -*-
"""Copy of haralick.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1AQh8i5vb85xp5Wj4SgwJfyBfuw1KpD8G
"""

!pip install mahotas

from google.colab import drive
drive.mount('/gdrive')

import mahotas as mt # for haralick feature extraction
import cv2 # image processing
import pandas as pd # data manipulation
import numpy as np # numerical operations
from skimage.feature import greycomatrix, greycoprops # image related functions
from skimage import io, color, img_as_ubyte
import csv
import glob
import os

def extract_features(image):
    """Extracts the Haralick texture features for a given image.

    Args:
        image: A numpy array representing the image.

    Returns:
        A numpy array containing the Haralick texture features.
    """

    # calculate haralick texture features for 4 types of adjacency
    textures = mt.features.haralick(image)

    # take the mean of it and return it
    ht_mean = textures.mean(axis=0)
    return ht_mean

output_filename = "/gdrive/MyDrive/Breast Cancer DataSET/haralick_features/Haralick_normal_10_0.csv"

# add the column headings to the CSV file
with open(output_filename, 'a', newline='') as csvfile:
    csvwriter = csv.writer(csvfile)
    csvwriter.writerow(['ASM', 'CON', 'COR', 'VAR', 'IDM', 'SAV', 'SVA', 'SEN', 'ENT', 'DVA', 'DEN', 'F12', 'F13'])

# Specify the folder containing your images
image_folder = "/gdrive/MyDrive/Breast Cancer DataSET/roi/10"

# Iterate over all the images in the specified folder and extract the Haralick texture features
for image_path in glob.glob(os.path.join(image_folder, "*.png")):
    img = cv2.imread(image_path)
    img = cv2.resize(img, None, fx=0.5, fy=0.5, interpolation=cv2.INTER_AREA)
    img = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
    f = extract_features(img)
    row = [f[0], f[1], f[2], f[3], f[4], f[5], f[6], f[7], f[8], f[9], f[10], f[11], f[12]]

    # write the extracted features to the CSV file
    with open(output_filename, 'a', newline='') as csvfile:
        csvwriter = csv.writer(csvfile)
        csvwriter.writerow(row)

import pandas as pd

# Load the CSV file into a Pandas DataFrame
filename = "/gdrive/MyDrive/Breast Cancer DataSET/haralick_features/Haralick_normal_10_0.csv"
df = pd.read_csv(filename)
# Display the DataFrame, including column names
print("CSV File Contents:")
print(df)

# Commented out IPython magic to ensure Python compatibility.
import pandas as pd

# Load the CSV file into a Pandas DataFrame
filename = "/content/Haralick_normal9_0.csv"
df = pd.read_csv(filename)

# %cd /gdrive/My Drive/Colab Notebooks
# %cp -av /gdrive/MyDrive/Breast\ Cancer\ DataSET/haralick_features .
# Display the DataFrame, including column names
print("CSV File Contents:")
print(df)