# -*- coding: utf-8 -*-
"""Copy of img_ext.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Kr2wmG_eVsBhuwkzC0Y_K7XQA0KnPoNe
"""

from google.colab import drive
drive.mount('/gdrive')

"""# New Section"""

import h5py

# Path to the HDF5 file
path = "/gdrive/MyDrive/Breast Cancer DataSET/image files (.h5 files)/10.h5"

# Open the HDF5 file
hdf5_file = h5py.File(path, 'r')

# Specify the name of the dataset you want to access (in this case, "bags")
dataset_name = "label"

# Check if the dataset exists in the file
if dataset_name in hdf5_file:
    # Access the dataset
    dataset = hdf5_file[dataset_name]

    # Display the contents of the dataset (assuming it's a 2D dataset)
    print(f"Contents of the '{dataset_name}' dataset:")
    print(dataset[:])  # Display all rows and columns

    # If the dataset is very large, you can display a subset
    # For example, display the first 10 rows and all columns
    # print(dataset[:10, :])

else:
    print(f"The dataset '{dataset_name}' does not exist in the HDF5 file.")

# Close the HDF5 file when done
hdf5_file.close()

import h5py
import matplotlib.pyplot as plt
import os

# Open the HDF5 file
hdf5_file = h5py.File(path, 'r')

# Specify the name of the dataset containing images (e.g., "bags")
dataset_name = "bag"

# Check if the dataset exists in the file
if dataset_name in hdf5_file:
    # Access the dataset
    dataset = hdf5_file[dataset_name]

    # Create a directory to save the images if it doesn't exist
    save_dir = '/gdrive/MyDrive/Breast Cancer DataSET/image files (.h5 files)/10.h5'
    os.makedirs(save_dir, exist_ok=True)

    # Iterate through the images in the dataset and save them
    for i in range(len(dataset)):
        image_data = dataset[i]  # Assuming each entry in the dataset is an image
        plt.imshow(image_data.transpose(1, 2, 0))  # Transpose to (224, 224, 3) for displaying RGB image
        plt.title(f"Image {i + 1}")
        plt.axis('off')  # Turn off axis labels and ticks

        # Save the image to the directory
        image_filename = os.path.join(save_dir, f"image_{i + 1}.png")
        plt.savefig(image_filename, bbox_inches='tight', pad_inches=0)

        # Clear the current plot to display the next image
        plt.clf()

    print(f"{len(dataset)} images saved to '{save_dir}' directory in Google Colab.")

else:
    print(f"The dataset '{dataset_name}' does not exist in the HDF5 file.")

# Close the HDF5 file when done
hdf5_file.close()

# Commented out IPython magic to ensure Python compatibility.
#path that contains folder you want to copy
# %cd /gdrive/My Drive/Colab Notebooks
# %cp -av /content/downloaded_images/img1/ imgext72_0